services:
  - type: web
    name: iglesia-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
    disks:
      - name: iglesia-data
        mountPath: /data
        sizeGB: 1